name: Build and push

on:
  pull_request:
    types: [closed]
    branches: master

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Re-tag
      run: |
        docker pull analysiscenter1/ds-py3:latest
        docker tag analysiscenter1/ds-py3:latest analysiscenter1/ds-py3:backup
        echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push analysiscenter1/ds-py3:backup

    - name: Build
      run: docker build build -t analysiscenter1/ds-py3

    - name: Push
      run: |
        echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push analysiscenter1/ds-py3
