name: Build and push

on:
  pull_request:
    types: [closed]
    branches: cpu
    
jobs:

  build-push:
 
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: docker build build -t analysiscenter1/ds-py3:cpu

    - name: Push
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
        docker push analysiscenter1/ds-py3:cpu
