name: Build

on:
  pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.11]

    steps:
    - uses: actions/checkout@v2

    - run: | 
        docker build build \
          -t analysiscenter1/ds-py3:${{ matrix.python }} --build-arg PYTHON_VERSION=${{ matrix.python }}
