name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    
    container:
      image: analysiscenter1/ds-py3:cpu
  
    steps:
    - uses: actions/checkout@v1
    - run: ps -ef
