name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: analysiscenter1/ds-py3
 
    steps:
    - uses: actions/checkout@v1
    - uses: docker://analysiscenter1/ds-py3:cpu
      run: ps -ef
