name: Build and push

on:
  pull_request:
    types: [closed]
    branches: master

jobs:

  build-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build build -t analysiscenter1/ds-py3:latest -t analysiscenter1/ds-py3:$(echo ${{github.sha}} | cut -c1-7)

    - name: Push
      run: |
        echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push analysiscenter1/ds-py3 --all-tags

