name: Build and push

on:
  pull_request:
    types: [closed]
    branches: master

jobs:

  build-push:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python: [3.8, 3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker build build \
          -t analysiscenter1/ds-py3:${{ matrix.python }}  --build-arg PYTHON_VERSION=${{ matrix.python }} \
          -t analysiscenter1/ds-py3:${{ matrix.python }}_$(echo ${{github.sha}} | cut -c1-7) --build-arg PYTHON_VERSION=${{ matrix.python }}

    - name: Push
      run: |
        echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
        docker push analysiscenter1/ds-py3 --all-tags

